---
- hosts: all
  tasks:
  # Intentionaly meant to fail to show an example.
    - name: set waiting limit
      command: /bin/sleep 10
      async: 20
      poll: 5
    - name: do something
      debug:
        msg: we are still wating
