---
- name: Install CentOS/RHEL dependecies
  hosts: all

  tasks:
    # - name: Enable EPEL Repository on CentOS 8
    #   dnf:
    #     name: epel-release
    #     state: latest
    #     # become: True
    #   when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
    - name: Enable EPEL Repository on CentOS 7
      yum:
        name: epel-release
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
    - name: install the packages
      yum:
        name: "{{ packages }}"
        state: latest
        disablerepo: "epel"
        update_cache: yes
        # validate_certs: no
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

    - name: Install Docker
      include: install_docker.yml
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
